- hosts: local
  pre_tasks:
    - name: Update OS packages
      become: yes
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
        upgrade: dist
  roles:
    - core
    - dotfiles
    - role: asdf
      tags: asdf
    - gnome
    - neovim
    - role: lsp
      tags: lsp
    - fonts
