- name: Install stow
  become: yes
  ansible.builtin.apt:
    name: stow
    state: present
  tags: dotfiles

- name: Clone dotfiles
  ansible.builtin.git:
    repo: git@github.com:drewreeve/dotfiles.git
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: master
  tags: dotfiles

- name: Install dotfiles
  ansible.builtin.command: ./install
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.dotfiles"
  tags: dotfiles
