# Needed for setting dconf values
- name: Install additional packages for ansible
  apt:
    name: "python3-psutil"
    state: present

- name: Enable night light
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: 'true'
    state: present

- name: Set night light temperature
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
    value: 'uint32 3200'
    state: present

- name: Disable night light automatic schedule
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic
    value: 'false'
    state: present

- name: Set night light start time
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-from
    value: '21.0'
    state: present

- name: Set night light end time
  community.general.dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-schedule-to
    value: '6.0'
    state: present

- name: Set keyboard options
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:nocaps']"
    state: present

- name: Set clock format
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
    state: present

# Terminal config
- name: Read existing terminal profiles
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    state: read
  register: existing_terminal_profiles



- name: Generate profile list
  set_fact:
    terminal_profiles: |-
      {{ existing_terminal_profiles.value | regex_findall("'(.*?)'") }}

- name: Append new profile to list
  set_fact:
    terminal_profiles: "{{ terminal_profiles|default([]) + terminal.profile_id  }}"

- name: Write profile list
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/list"
    value: "{{ terminal_profiles|unique|string }}"
    state: present

- name: Write profile settings
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal.profile_id | first }}/{{ item.key|string }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ terminal.profile_settings | dict2items }}"
